const DRAFT_ORDER = [
  { pick: 1,  player: "Austin", groups: [1, 2, 4] },
  { pick: 2,  player: "Casey",  groups: [1, 2, 3, 4] },
  { pick: 3,  player: "Mike",   groups: [1, 3, 4] },
  { pick: 4,  player: "Mike",   groups: [1, 3, 4] },
  { pick: 5,  player: "Casey",  groups: [1, 2, 3, 4] },
  { pick: 6,  player: "Austin", groups: [1, 2, 4] },
  { pick: 7,  player: "Austin", groups: [2] },
  { pick: 8,  player: "Casey",  groups: [2] },
  { pick: 9,  player: "Casey",  groups: [2] },
  { pick: 10, player: "Austin", groups: [3] },
  { pick: 11, player: "Kenny",  groups: [3] },
  { pick: 12, player: "Tyler",  groups: [3] },
  { pick: 13, player: "Mike",   groups: [3] },
  { pick: 14, player: "Mike",   groups: [3] },
  { pick: 15, player: "Tyler",  groups: [3] },
  { pick: 16, player: "Kenny",  groups: [3] },
  { pick: 17, player: "Lev",    groups: [4] },
  { pick: 18, player: "Tyler",  groups: [4] },
  { pick: 19, player: "Tyler",  groups: [4] },
  { pick: 20, player: "Lev",    groups: [4] },
];

const PLAYERS = ["Austin", "Casey", "Mike", "Kenny", "Tyler", "Lev"];

const GOLFER_POOL = [
  "Scottie Scheffler",
  "Rory McIlroy",
  "Xander Schauffele",
  "Collin Morikawa",
  "Viktor Hovland",
  "Jon Rahm",
  "Brooks Koepka",
  "Ludvig Aberg",
  "Patrick Cantlay",
  "Wyndham Clark",
  "Tommy Fleetwood",
  "Shane Lowry",
  "Hideki Matsuyama",
  "Justin Thomas",
  "Jordan Spieth",
  "Tony Finau",
  "Max Homa",
  "Will Zalatoris",
  "Sahith Theegala",
  "Tom Kim",
  "Sungjae Im",
  "Cameron Young",
  "Brian Harman",
  "Jason Day",
  "Matt Fitzpatrick",
  "Tyrrell Hatton",
  "Robert MacIntyre",
  "Adam Scott",
  "Russell Henley",
  "Keegan Bradley",
  "Si Woo Kim",
  "Min Woo Lee",
  "Cameron Smith",
  "Dustin Johnson",
  "Phil Mickelson",
  "Tiger Woods",
  "Patrick Reed",
  "Sergio Garcia",
  "Bubba Watson",
  "Danny Willett",
  "Charl Schwartzel",
  "Justin Rose",
  "Louis Oosthuizen",
  "Corey Conners",
  "Sepp Straka",
  "Sam Burns",
  "Akshay Bhatia",
  "Denny McCarthy",
  "Joaquin Niemann",
  "Christiaan Bezuidenhout",
  "Billy Horschel",
  "Nick Taylor",
  "Maverick McNealy",
  "Stephan Jaeger",
  "Aaron Rai",
  "Lucas Glover",
  "Talor Gooch",
  "Davis Thompson",
  "Eric Cole",
  "Taylor Moore",
  "Cam Davis",
  "K.H. Lee",
  "Nick Dunlap",
  "Rasmus Hojgaard",
  "Nicolai Hojgaard",
  "Thomas Detry",
  "Emiliano Grillo",
  "Erik van Rooyen",
  "Sebastian Munoz",
  "Rickie Fowler",
  "Ryo Hisatsune",
  "Thriston Lawrence",
  "Alex Noren",
  "Mike Weir",
  "Zach Johnson",
  "Fred Couples",
  "Larry Mize",
  "Bernhard Langer",
  "Vijay Singh",
  "Jose Maria Olazabal",
  "Sandy Lyle",
  "Mark O'Meara",
  "Fuzzy Zoeller",
  "Ben Crenshaw",
  "Tom Watson",
  "Byeong Hun An",
  "Seonghyeon Kim",
  "Jake Knapp",
  "Michael Thorbjornsen",
  "Matthieu Pavon",
  "Taylor Pendrith",
  "Austin Eckroat",
  "Harris English",
  "Brendon Todd",
  "Luke Donald",
  "Zach Johnson",
  "Chris Kirk",
];

// Deduplicate
const uniqueGolfers = [...new Set(GOLFER_POOL)].sort();

const GROUP_NAMES = {
  1: "Group 1",
  2: "Group 2",
  3: "Group 3",
  4: "Group 4",
};

module.exports = { DRAFT_ORDER, PLAYERS, GOLFER_POOL: uniqueGolfers, GROUP_NAMES };
