const DRAFT_ORDER = [
  { pick: 1,  player: "Austin", groups: [1, 2, 4] },
  { pick: 2,  player: "Casey",  groups: [1, 2, 3, 4] },
  { pick: 3,  player: "Mike",   groups: [1, 3, 4] },
  { pick: 4,  player: "Mike",   groups: [1, 3, 4] },
  { pick: 5,  player: "Casey",  groups: [1, 2, 3, 4] },
  { pick: 6,  player: "Austin", groups: [1, 2, 4] },
  { pick: 7,  player: "Austin", groups: [2] },
  { pick: 8,  player: "Casey",  groups: [2] },
  { pick: 9,  player: "Casey",  groups: [2] },
  { pick: 10, player: "Austin", groups: [3] },
  { pick: 11, player: "Kenny",  groups: [3] },
  { pick: 12, player: "Tyler",  groups: [3] },
  { pick: 13, player: "Mike",   groups: [3] },
  { pick: 14, player: "Mike",   groups: [3] },
  { pick: 15, player: "Tyler",  groups: [3] },
  { pick: 16, player: "Kenny",  groups: [3] },
  { pick: 17, player: "Lev",    groups: [4] },
  { pick: 18, player: "Tyler",  groups: [4] },
  { pick: 19, player: "Tyler",  groups: [4] },
  { pick: 20, player: "Lev",    groups: [4] },
];

const PLAYERS = ["Austin", "Casey", "Mike", "Kenny", "Tyler", "Lev"];

const GOLFER_POOL = [
  "Ludvig Aberg",
  "Daniel Berger",
  "Akshay Bhatia",
  "Keegan Bradley",
  "Michael Brennan",
  "Jacob Bridgeman",
  "Sam Burns",
  "Angel Cabrera",
  "Brian Campbell",
  "Patrick Cantlay",
  "Wyndham Clark",
  "Corey Conners",
  "Fred Couples",
  "Jason Day",
  "Bryson DeChambeau",
  "Nico Echavarria",
  "Harris English",
  "Ethan Fang",
  "Matt Fitzpatrick",
  "Tommy Fleetwood",
  "Ryan Fox",
  "Sergio Garcia",
  "Ryan Gerard",
  "Christopher Gotterup",
  "Max Greyserman",
  "Ben Griffin",
  "Harry Hall",
  "Brian Harman",
  "Tyrrell Hatton",
  "Russell Henley",
  "Jackson Herrington",
  "Nicolai Hojgaard",
  "Rasmus Hojgaard",
  "Brandon Holtz",
  "Max Homa",
  "Viktor Hovland",
  "Mason Howell",
  "Sungjae Im",
  "Casey Jarvis",
  "Dustin Johnson",
  "Zach Johnson",
  "Naoyuki Kataoka",
  "John Keefer",
  "Si Woo Kim",
  "Michael Kim",
  "Kurt Kitayama",
  "Jake Knapp",
  "Brooks Koepka",
  "Fifa Laopakdee",
  "Min Woo Lee",
  "Haotong Li",
  "Shane Lowry",
  "Robert MacIntyre",
  "Hideki Matsuyama",
  "Matt McCarty",
  "Rory McIlroy",
  "Tom McKibbin",
  "Maverick McNealy",
  "Collin Morikawa",
  "Rasmus Neergaard-Petersen",
  "Alex Noren",
  "Andrew Novak",
  "Jose Maria Olazabal",
  "Carlos Ortiz",
  "Marco Penge",
  "Aldrich Potgieter",
  "Mateo Pulcini",
  "Jon Rahm",
  "Aaron Rai",
  "Patrick Reed",
  "Kristoffer Reitan",
  "Davis Riley",
  "Justin Rose",
  "Xander Schauffele",
  "Scottie Scheffler",
  "Charl Schwartzel",
  "Adam Scott",
  "Vijay Singh",
  "Cameron Smith",
  "J.J. Spaun",
  "Jordan Spieth",
  "Sam Stevens",
  "Sepp Straka",
  "Nick Taylor",
  "Justin Thomas",
  "Sami Valimaki",
  "Bubba Watson",
  "Mike Weir",
  "Danny Willett",
  "Gary Woodland",
  "Cameron Young",
];

// Deduplicate
const uniqueGolfers = [...new Set(GOLFER_POOL)].sort();

const GROUP_NAMES = {
  1: "Group 1",
  2: "Group 2",
  3: "Group 3",
  4: "Group 4",
};

module.exports = { DRAFT_ORDER, PLAYERS, GOLFER_POOL: uniqueGolfers, GROUP_NAMES };
